# Generated by Django 3.2.16 on 2025-08-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'default_related_name': 'ingredient', 'ordering': ('name',), 'verbose_name': 'ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_user_shopping_cart',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('holder', 'recipe'), name='favorite_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('holder', 'recipe'), name='shoppingcart_user_unique'),
        ),
    ]
